demos/blog/blog/blueprints/admin.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@File    :   admin.py
@Time    :   2024/07/24 16:55:45
@Author  :   Alan
@Desc    :   None
'''
import os
from datetime import UTC, datetime

from flask import Blueprint, current_app, flash, jsonify, redirect, render_template, request, send_from_directory, url_for
from flask_login import current_user, login_required
from flask_ckeditor import upload_success, upload_fail

from blog.extensions import db
from blog.forms import CategoryForm, PostForm, LinkForm, SettingsForm
from blog.models import Category, Comment, Link, Post
from blog.utils import allowed_file, redirect_back

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/post/manage')
@login_required
def manage_post():
  page = request.args.get('page', 1, type=int)
  per_page = request.args.get('per_page', current_app.config['BLOG_MANAGE_POST_PER_PAGE'], type=int)
  pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=per_page)
  posts = pagination.items
  return render_template('admin/manage_post.html', posts=posts, page=page, pagination=pagination)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
  form = PostForm()
  if form.validate_on_submit():
    title = form.title.data
    body = form.body.data
    category = Category.query.get(form.category.data)
    post = Post(title=title, body=body, category=category)
    db.session.add(post)
    db.session.commit()
    flash('Post created.', 'success')
    return redirect(url_for('essay.show_post', post_id=post.id))
  return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/set-comment', methods=['POST'])
@login_required
def set_comment(post_id):
  post = Post.query.get_or_404(post_id)
  if post.can_comment:
    post.can_comment = False
    flash('Comment disabled', 'success')
  else:
    post.can_comment = True 
    flash('Comment enabled', 'success')
  db.session.commit()
  return redirect_back()


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
  post = Post.query.get_or_404(post_id)
  form = PostForm()
  if form.validate_on_submit():
    post.title = form.title.data
    post.category = Category.query.get_or_404(form.category.data)
    post.body = form.body.data
    post.timestamp = datetime.now(UTC)
    db.session.commit()
    flash('Updated post', 'success')
    return redirect(url_for('essay.show_post', post_id=post.id))
  form.title.data = post.title
  form.category.data = post.category_id
  form.body.data = post.body
  return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  db.session.delete(post)
  db.session.commit()
  flash('Deleted post.', 'success')
  return redirect_back()


@admin_bp.route('/category/manage')
@login_required
def manage_category():
  return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
  form = CategoryForm()
  if form.validate_on_submit():
    name = form.name.data
    category = Category(name=name)
    db.session.add(category)
    db.session.commit()
    flash('Created category~', 'success')
    return redirect(url_for('.manage_category'))
  return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
  category = Category.query.get_or_404(category_id)
  form = CategoryForm()
  if form.validate_on_submit():
    category.name = form.name.data
    db.session.commit()
    flash('Updated category.', 'success')
  form.name.data = category.name
  return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
  category = Category.query.get_or_404(category_id)
  # db.session.delete(category)
  # db.session.commit()
  category.delete()
  flash('Deleted category', 'success')
  return redirect_back()


@admin_bp.route('/comment/manage')
@login_required
def manage_comment():
  page = request.args.get('page', 1, type=int)
  per_page = request.args.get('per_page', current_app.config['BLOG_MANAGE_POST_PER_PAGE'], type=int)
  filter_rule = request.args.get('filter', 'all') # 'all', 'unread' and 'admin'
  if filter_rule == 'unread':
    filtered_comments = Comment.query.filter(Comment.reviewed==False)
  elif filter_rule == 'admin':
    filtered_comments = Comment.query.filter_by(from_admin=True)
  else:
    filtered_comments = Comment.query
  pagination = filtered_comments \
    .order_by(Comment.timestamp.desc()) \
    .paginate(page=page, per_page=per_page)
  comments = pagination.items
  return render_template('admin/manage_comment.html', comments=comments, page=page, pagination=pagination)


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
  comment = Comment.query.get_or_404(comment_id)
  comment.reviewed = True
  db.session.commit()
  flash('Comment published', 'success')
  return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
  comment = Comment.query.get_or_404(comment_id)
  db.session.delete(comment)
  db.session.commit()
  flash('Comment deleted', 'success')
  return redirect_back()


@admin_bp.route('/link/manage')
@login_required
def manage_link():
  return render_template('admin/manage_link.html')

@admin_bp.route('/link/new', methods=['GET', 'POST'])
@login_required
def new_link():
  form = LinkForm()
  if form.validate_on_submit():
    name = form.name.data
    url = form.url.data
    link = Link(name=name, url=url)
    db.session.add(link)
    db.session.commit()
    flash('Created Link.', 'success')
    return redirect(url_for('.manage_link'))
  return render_template('admin/new_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_link(link_id):
  link = Link.query.get_or_404(link_id)
  form = LinkForm()
  if form.validate_on_submit():
    link.name = form.name.data
    link.url = form.url.data
    db.session.commit()
    flash('Updated Link', 'success')
    return redirect(url_for('.manage_link'))
  form.name.data = link.name
  form.url.data = link.url
  return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
def delete_link(link_id):
  link = Link.query.get_or_404(link_id)
  db.session.delete(link)
  db.session.commit()
  flash('Deleted link.', 'success')
  return redirect(url_for('.manage_link'))


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
  form = SettingsForm()
  if form.validate_on_submit():
    current_user.name = form.name.data
    current_user.blog_title = form.blog_title.data
    current_user.blog_sub_title = form.blog_sub_title.data
    current_user.about = form.about.data
    db.session.commit()
    flash('Settings updated.', 'success')
    return redirect(url_for('essay.index'))
  form.name.data = current_user.name
  form.blog_title.data = current_user.blog_title
  form.blog_sub_title.data = current_user.blog_sub_title
  form.about.data = current_user.about
  return render_template('admin/settings.html', form=form)


@admin_bp.route('/upload', methods=['POST'])
@login_required
def upload_image():
  f = request.files.get('upload')
  if not allowed_file(f.filename):
    return upload_fail('image only~')
  f.save(os.path.join(current_app.config['BLOG_UPLOAD_PATH'], f.filename))
  url = url_for('.get_image', filename=f.filename)
  return upload_success(url, f.filename)


@admin_bp.route('/uploads/<path:filename>')
def get_image(filename):
  return send_from_directory(current_app.config['BLOG_UPLOAD_PATH'], filename)

demos/blog/blog/blueprints/essay.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@File    :   essay.py
@Time    :   2024/07/24 11:46:08
@Author  :   Alan
@Desc    :   None
'''
from flask import Blueprint, abort, current_app, flash, make_response, redirect, render_template, request, url_for
from flask_login import current_user

from blog.extensions import db
from blog.models import Admin, Category, Comment, Post
from blog.forms import AdminCommentForm, CommentForm
from blog.utils import redirect_back
from blog.emails import send_new_comment_email, send_new_reply_email

essay_bp = Blueprint('essay', __name__)


@essay_bp.route('/')
def index():
  page = request.args.get('page', 1, type=int)
  per_page = request.args.get('per_page', current_app.config['BLOG_POST_PER_PAGE'], type=int)
  pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page=page, per_page=per_page)
  posts = pagination.items
  return render_template('essay/index.html', pagination=pagination, posts=posts)


@essay_bp.route('/about')
def about():
  return render_template('essay/about.html')


@essay_bp.route('/category/<int:category_id>')
def show_category(category_id):
  category = Category.query.get_or_404(category_id)
  page = request.args.get('page', 1, type=int)
  per_page = request.args.get('per_page', current_app.config['BLOG_POST_PER_PAGE'], type=int)
  pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(page=page, per_page=per_page)
  posts = pagination.items
  return render_template('essay/category.html', category=category, pagination=pagination, posts=posts)


@essay_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
  post = Post.query.get_or_404(post_id)
  page = request.args.get('page', 1, type=int)
  per_page = request.args.get('per_page', current_app.config['BLOG_POST_PER_PAGE'], type=int)
  pagination = Comment.query.with_parent(post).order_by(Comment.timestamp.desc()).paginate(page=page, per_page=per_page)
  comments = pagination.items

  if current_user.is_authenticated:
    form = AdminCommentForm()
    form.author.data = current_user.name
    form.email.data = current_app.config['BLOG_EMAIL']
    form.site.data = url_for('.index')
    from_admin = True
    reviewed = True
  else:
    form = CommentForm()
    from_admin = False
    reviewed = False

  if form.validate_on_submit():
    author = form.author.data
    email = form.email.data
    site = form.site.data
    body = form.body.data
    comment = Comment(
      author=author,
      email=email,
      site=site,
      body=body,
      post=post,
      from_admin=from_admin,
      reviewed=reviewed
    )
    replied_id = request.args.get('reply')
    if replied_id:
      replied_comment = Comment.query.get_or_404(replied_id)
      comment.replied = replied_comment
      # send notification email that his comment has been replied to the comment author
      send_new_reply_email(replied_comment)
    db.session.add(comment)
    db.session.commit()
    if current_user.is_authenticated:
      flash('Comment published.', 'success')
    else:
      flash('Thanks, your comment will be published after reviewed.', 'info')
      # send notification email to admin
      send_new_comment_email(post) 
    return redirect(url_for('.show_post', post_id=post_id))
  return render_template('essay/post.html', pagination=pagination, post=post, comments=comments, form=form)


@essay_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
  comment = Comment.query.get_or_404(comment_id)
  if not comment.post.can_comment:
    return redirect(url_for('.show_post', post_id=comment.post.id))
  return redirect(
    url_for(
      '.show_post',
      post_id=comment.post.id,
      reply=comment_id,
      author=comment.author
    ) + '#comment-form'
  )


@essay_bp.route('/theme/<string:theme_name>')
def change_theme(theme_name):
  if theme_name not in current_app.config['BLOG_THEMES'].keys():
    abort(404)
  response = make_response(redirect_back())
  if current_user.is_authenticated:
    admin = Admin.query.get_or_404(current_user.id)
    admin.theme = theme_name
    db.session.commit()
  else:
    response.set_cookie('theme', theme_name, max_age = 30 * 24 * 60 * 60)
  return response

demos/blog/blog/templates/essay/_posts.html
{% if posts %}
  {% for post in posts %}
    <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
    <p>
      {{ post.body|striptags|truncate }}
      <small><a href="{{ url_for('.show_post', post_id=post.id) }}">Read More</a></small>
    </p>
    <small>
      Comments: <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
      Category: <a
        href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
      <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
    </small>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% else %}
  <div class="tip">
    <h5>No posts yet.</h5>
    {% if current_user.is_authenticated %}
      <a href="{{ url_for('admin.new_post') }}">Write Now</a>
    {% endif %}
  </div>
{% endif %}

demos/blog/blog/templates/essay/_sidebar.html
{% if links %}
  <div class="card mb-3">
    <div class="card-header">Links</div>
    <ul class="list-group list-group-flush">
      {% for link in links %}
        <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
          <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

{% if categories %}
  <div class="card mb-3">
    <div class="card-header">Categories</div>
    <ul class="list-group list-group-flush">
      {% for category in categories %}
        <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
          <a href="{{ url_for('essay.show_category', category_id=category.id) }}">
            {{ category.name }}
          </a>
          <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
        </li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

<div class="dropdown">
  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Change Theme
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    {% for theme_name, display_name in config.BLOG_THEMES.items() %}
      <a class="dropdown-item"
        href="{{ url_for('essay.change_theme', theme_name=theme_name, next=request.full_path) }}">
        {{ display_name }}</a>
    {% endfor %}
  </div>
</div>

demos/blog/blog/templates/essay/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
  <div class="page-header">
    <h1>About</h1>
  </div>
  <div class="row">
      <div class="col-sm-8">
        {{ admin.about|safe }}
      </div>
      <div class="col-sm-4 sidebar">
        {% include 'essay/_sidebar.html' %}
      </div>
  </div>
{% endblock content %}

demos/blog/blog/templates/essay/category.html
{% extends 'base.html' %}
{% from 'bootstrap4/pagination.html' import render_pagination %}

{% block title %}{{category.name}}{% endblock title %}

{% block content %}
  <div class="page-header">
    <h1>Category: {{ category.name }}</h1>
    <p class="text-muted">{{ category.posts|length }} posts</p>
  </div>
  <div class="row">
    <div class="col-sm-8">
      {% include 'essay/_posts.html' %}
      <div class="page-footer">{{ render_pagination(pagination) }}</div>
    </div>
    <div class="col-sm-4">
      {% include 'essay/_sidebar.html' %}
    </div>
  </div>
{% endblock content %}

demos/blog/blog/templates/essay/index.html
{% extends 'base.html'  %}
{% from 'bootstrap4/pagination.html' import render_pagination %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="page-header">
  <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
  <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
</div>
<div class="row">
  <div class="col-sm-8">
    {% include 'essay/_posts.html' %}
    {% if posts %}
      <div class="page-footer">{{ render_pagination(pagination) }}</div>
    {% endif %}
  </div>
  <div class="col-sm-4 sidebar">
    {% include 'essay/_sidebar.html' %}
  </div>
</div>
{% endblock %}

demos/blog/blog/templates/essay/post.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}
{% from 'bootstrap4/pagination.html' import render_pagination %}

{% block title %}{{post.title}}{% endblock title %}

{% block content %}
  <div class="page-header">
    <h1 class="d-flex justify-content-between align-items-center">
      <span>{{ post.title }}</span>
      {% if current_user.is_authenticated %}
      <div class="d-flex align-items-center">
        <a href="{{ url_for('admin.edit_post', post_id=post.id) }}" class="btn btn-info btn-sm mr-2">Edit</a>
        <form style="font-size: 0;" action="{{ url_for('admin.delete_post', post_id=post.id, next=url_for('essay.index')) }}">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
          <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete</button>
        </form>
      </div>
      {% endif %}
    </h1>
    <small>
      Category:<a href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a><br />
      Date: {{ moment(post.timestamp).format('LL') }}
    </small>
  </div>
  <div class="row">
    <div class="col-sm-8">
      {{ post.body|safe }}
      <hr />
      <div class="d-flex justify-content-end mb-2">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#post-link-modal">Share</button>
        <!-- Modal -->
        <div class="modal fade" id="post-link-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Permalink</h1>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close">&times;</button>
              </div>
              <div class="modal-body">
                <div class="form-group">
                  <input type="text" class="form-control" value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="mb-3 comments" id="comments">
        <h3>
          {{ pagination.total }} comments
          <small>
            <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">latest</a>
          </small>
          {% if current_user.is_authenticated %}
            <form action="{{ url_for('admin.set_comment', post_id=post.id, next=request.full_path) }}" class="float-right" method="post">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <button type="submit" class="btn btn-warning btn-sm">
                {% if post.can_comment %}Disable{% else %}Enable{% endif %}Comment
              </button>
            </form>
          {% endif %}
        </h3>
        {% if comments %}
          <ul class="list-group">
            {% for comment in comments %}
              <li class="list-group-item list-group-item-action flex-column">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">
                    <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}" target="_blank">
                      {% if comment.from_admin %}
                        {{ admin.name }}
                      {% else %}
                        {{ comment.author }}
                      {% endif %}
                    </a>
                    {% if comment.from_admin %}<span class="badge badge-primary">Author</span>{% endif %}
                    {% if comment.replied %}<span class="badge badge-light">Reply</span>{% endif %}
                  </h5>
                  <small data-toggle="tooltip" data-placement="top" data-delay="500"
                    data-timestap="{{ comment.timestamp.strftime('%Y/%m/%dT%H:%M:%SZ') }}">
                    {{ moment(comment.timestamp).fromNow(refresh=True) }}
                  </small>
                </div>
                {% if comment.replied %}
                  <p class="alert alert-dark reply-body">
                    {{ comment.replied.author }}:<br />
                    {{ comment.replied.body }} 
                  </p>
                {%- endif -%}
                <p class="mb-1">{{ comment.body }}</p>
                <div class="float-right d-flex align-items-center">
                  <a class="btn btn-light btn-sm" href="{{ url_for('.reply_comment', comment_id=comment.id) }}">Reply</a>
                  {% if current_user.is_authenticated %}
                    <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                    <form class="inline" method="post" action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                      <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?');">Delete</button>
                    </form>
                  {% endif %}
                </div>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <div class="tip"><h5>No comments.</h5></div>
        {% endif %}
      </div>
      {% if comments %}
        {{ render_pagination(pagination, fragment='#comments') }}
      {% endif %}
      {% if request.args.get('reply') %}
        <div class="alert alert-dark">
          Reply to <strong>{{ request.args.get('author') }}</strong>:
          <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">Cancel</a>
        </div>
      {% endif %}
      {% if post.can_comment %}
        <div id="comment-form">
          {{ render_form(form, action=request.full_path) }}
        </div>
      {% else %}
        <div class="tip"><h5>Comment disabled.</h5></div>
      {% endif %}
    </div>
    <div class="col-sm-4 sidebar">
      {% include 'essay/_sidebar.html' %}
    </div>
  </div>
{% endblock content %}
 