demos/albumy/albumy/blueprints/admin.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@File    :   admin.py
@Time    :   2024/08/06 15:57:45
@Author  :   Alan
@Desc    :   None
'''
from flask import Blueprint, render_template, flash, request, current_app
from flask_login import login_required

from albumy.models import User, Photo, Tag, Comment
from albumy.decorators import admin_required, permission_required
from albumy.models import Role
from albumy.extensions import db
from albumy.forms.admin import EditProfileAdminForm
from albumy.utils import redirect_back


admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/')
@login_required
@permission_required('MODERATE')
def index():
  user_count = User.query.count()
  locked_user_count = User.query.filter_by(locked=True).count()
  blocked_user_count = User.query.filter_by(active=False).count()
  photo_count = Photo.query.count()
  reported_photos_count = Photo.query.filter(Photo.flag > 0).count()
  tag_count = Tag.query.count()
  comment_count = Comment.query.count()
  reported_comments_count = Comment.query.filter(Comment.flag > 0).count()
  return render_template('admin/index.html',
                         user_count=user_count,
                         locked_user_count=locked_user_count,
                         blocked_user_count=blocked_user_count,
                         photo_count=photo_count,
                         reported_photos_count=reported_photos_count,
                         tag_count=tag_count,
                         comment_count=comment_count,
                         reported_comments_count=reported_comments_count)


@admin_bp.route('/profile/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_profile_admin(user_id):
  user = User.query.get_or_404(user_id)
  form = EditProfileAdminForm(user=user)
  if form.validate_on_submit():
    user.name = form.name.data
    role = Role.query.get(form.role.data)
    if role.name == 'Locked':
      user.lock()
    user.role = role
    user.bio = form.bio.data
    user.website = form.website.data
    user.confirmed = form.confirmed.data
    user.active = form.active.data
    user.location = form.location.data
    user.username = form.username.data
    user.email = form.email.data
    db.session.commit()
    flash('Profile updated.', 'success')
    return redirect_back()
  form.name.data = user.name
  form.role.data = user.role
  form.bio.data = user.bio
  form.website.data = user.website
  form.confirmed.data = user.confirmed
  form.active.data = user.active
  form.location.data = user.location
  form.username.data = user.username
  form.email.data = user.email
  return render_template('admin/edit_profile_admin.html', form=form, user=user)


@admin_bp.route('/block/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def block_user(user_id):
  user = User.query.get_or_404(user_id)
  if user.role.name in ['Administrator', 'Moderator']:
    flash('Permiss denied.', 'warning')
  else:
    user.block()
    flash('Account blocked.', 'info')
  return redirect_back()


@admin_bp.route('/unblock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unblock_user(user_id):
  user = User.query.get_or_404(user_id)
  user.unblock()
  flash('Block canceled.', 'info')
  return redirect_back()


@admin_bp.route('/lock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def lock_user(user_id):
  user = User.query.get_or_404(user_id)
  if user.role.name in ['Administrator', 'Moderator']:
    flash('Permission denied.', 'warning')
  else:
    user.lock()
    flash('Account locked.', 'info')
  return redirect_back()


@admin_bp.route('/unlock/user/<int:user_id>', methods=['POST'])
@login_required
@permission_required('MODERATE')
def unlock_user(user_id):
  user = User.query.get_or_404(user_id)
  user.unlock()
  flash('Lock canceled.', 'info')
  return redirect_back()


@login_required
@permission_required('MODERATE')
@admin_bp.route('/delete/tag/<int:tag_id>', methods=['GET', 'POST'])
def delete_tag(tag_id):
  tag = Tag.query.get_or_404(tag_id)
  db.session.delete(tag)
  db.session.commit()
  flash('Tag deleted.', 'info')
  return redirect_back()


@admin_bp.route('/manage/user')
@login_required
@permission_required('MODERATE')
def manage_user():
  # 'all', 'locked', 'blocked', 'administrator', 'moderator'
  filter_rule = request.args.get('filter', 'all')
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_MANAGE_USER_PER_PAGE']
  administrator = Role.query.filter_by(name='Administrator').first()
  moderator = Role.query.filter_by(name='Moderator').first()
  if filter_rule == 'locked':
    filter_users = User.query.filter_by(locked=True)
  elif filter_rule == 'blocked': 
    filter_users = User.query.filter_by(active=False)
  elif filter_rule == 'administrator':
    filter_users = User.query.with_parent(administrator)
  elif filter_rule == 'moderator':
    filter_users = User.query.with_parent(moderator)
  else:
    filter_users = User.query

  pagination = filter_users.order_by(User.member_since.desc()) \
                          .paginate(page=page, per_page=per_page)
  users = pagination.items
  return render_template('admin/manage_user.html', users=enumerate(users), pagination=pagination)


@admin_bp.route('/manage/photo', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/photo/<order>')
@login_required
@permission_required('MODERATE')
def manage_photo(order):
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_MANAGE_PHOTO_PER_PAGE']
  order_rule = 'flag'
  if order == 'by_time':
    pagination = Photo.query.order_by(Photo.timestamp.desc()) \
                              .paginate(page=page, per_page=per_page)
    order_rule = 'time'
  else:
    pagination = Photo.query.order_by(Photo.flag.desc()) \
                              .paginate(page=page, per_page=per_page)
  photos = pagination.items
  return render_template('admin/manage_photo.html', photos=enumerate(photos), pagination=pagination, order_rule=order_rule)


@admin_bp.route('/manage/tag', defaults={'order': 'desc'})
@admin_bp.route('/manage/tag/<order>')
@login_required
@permission_required('MODERATE')
def manage_tag(order):
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_MANAGE_TAG_PER_PAGE']
  order_rule = 'desc'
  if order == 'desc':
    pagination = Tag.query.order_by(Tag.id.desc()) \
                            .paginate(page=page, per_page=per_page)
  else:
    pagination = Tag.query.order_by(Tag.id.asc()) \
                            .paginate(page=page, per_page=per_page)
    order_rule = 'asc'
  tags = pagination.items
  return render_template('admin/manage_tag.html', tags=tags, pagination=pagination, order_rule=order_rule)


@admin_bp.route('/manage/comment', defaults={'order': 'by_flag'})
@admin_bp.route('/manage/comment/<order>')
@login_required
@permission_required('MODERATE')
def manage_comment(order):
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_MANAGE_COMMENT_PER_PAGE']
  order_rule = 'flag'
  if order == 'by_time':
    pagination = Comment.query.order_by(Comment.timestamp.desc()) \
                                .paginate(page=page, per_page=per_page)
    order_rule = 'time'
  else:
    pagination = Comment.query.order_by(Comment.flag.desc()) \
                                .paginate(page=page, per_page=per_page)
  comments = pagination.items
  return render_template('admin/manage_comment.html',
          pagination=pagination, comments=enumerate(comments), order_rule=order_rule)

demos/albumy/albumy/blueprints/main.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@File    :   main.py
@Time    :   2024/07/29 15:24:37
@Author  :   Alan
@Desc    :   None
'''
import os
from flask import Blueprint, abort, current_app, flash, redirect, render_template, request, send_from_directory, url_for
from flask_login import current_user, login_required
from sqlalchemy import func

from albumy.extensions import db, cache
from albumy.models import Collect, Comment, Follow, Notification, Photo, Tag, User
from albumy.forms.main import CommentForm, TagForm, DescriptionForm
from albumy.decorators import confirm_required, permission_required
from albumy.notifications import push_collect_notification, push_comment_notification
from albumy.utils import flash_errors, redirect_back, rename_image, resize_image


main_bp = Blueprint('main', __name__)


@main_bp.route('/')
@cache.cached(timeout=60*60)
def index():
  if current_user.is_authenticated:
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
    pagination = Photo.query \
      .join(Follow, Follow.followed_id == Photo.author_id) \
      .filter(Follow.follower_id == current_user.id) \
      .order_by(Photo.timestamp.desc()) \
      .paginate(page=page, per_page=per_page)
    photos = pagination.items
  else:
    pagination = None
    photos = None
  tags = Tag.query.join(Tag.photos).group_by(Tag.id) \
            .order_by(func.count(Photo.id).desc()).limit(10)
  return render_template('main/index.html',
                         photos=photos, pagination=pagination, tags=tags)


@main_bp.route('/explore')
def explore():
  photos = Photo.query.order_by(func.random()).limit(12) 
  return render_template('main/explore.html', photos=photos)


@main_bp.route('/search')
def search():
  q = request.args.get('q', '', type=str).strip()
  if q == '':
    flash('Enter keyword about photo, user or tag', 'warning')
    return redirect_back()
  
  category = request.args.get('category', 'photo')
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_PHOTO_PER_PAGE']
  if category == 'user':
    pagination = User.query.whooshee_search(q).paginate(page=page, per_page=per_page)
  elif category == 'tag':
    pagination = Tag.query.whooshee_search(q).paginate(page=page, per_page=per_page)
  else:
    pagination = Photo.query.whooshee_search(q).paginate(page=page, per_page=per_page)
  results = pagination.items
  return render_template('main/search.html',
                         q=q, results=results,
                         pagination=pagination, category=category)


@main_bp.route('/notifications')
@login_required
def show_notifications():
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_NOTIFICATION_PER_PAGE']
  notifications = Notification.query.with_parent(current_user)
  filter_rule = request.args.get('filter')
  if filter_rule == 'unread':
    notifications = notifications.filter_by(is_read=False)
  
  pagination = notifications.order_by(Notification.timestamp.desc()) \
    .paginate(page=page, per_page=per_page)
  notifications = pagination.items
  return render_template('main/notifications.html',
                         pagination=pagination, notifications=notifications)


@main_bp.route('/notification/read/<int:notification_id>', methods=['POST'])
@login_required
def read_notification(notification_id):
  notification = Notification.query.get_or_404(notification_id)
  if current_user != notification.receiver:
    abort(403)

  notification.is_read = True
  db.session.commit()
  flash('Notification archived.', 'success')
  return redirect(url_for('.show_notifications'))


@main_bp.route('/notifications/read/all', methods=['POST'])
@login_required
def read_all_notifications():
  for notification in current_user.notifications:
    notification.is_read = True
  db.session.commit()
  flash('Notifications all archived.', 'success')
  return redirect(url_for('.show_notifications'))
  

@main_bp.route('/uploads/<path:filename>')
def get_image(filename):
  return send_from_directory(current_app.config['ALBUMY_UPLOAD_PATH'], filename)


@main_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
  return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@main_bp.route('/upload', methods=['GET', 'POST'])
@login_required
@confirm_required
@permission_required('UPLOAD')
def upload():
  if request.method == 'POST' and 'file' in request.files:
    f = request.files.get('file')
    filename = rename_image(f.filename)
    f.save(os.path.join(current_app.config['ALBUMY_UPLOAD_PATH'], filename))
    filename_s = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['small'])
    filename_m = resize_image(f, filename, current_app.config['ALBUMY_PHOTO_SIZE']['medium'])
    photo = Photo(
      filename=filename,
      filename_s=filename_s,
      filename_m=filename_m,
      author=current_user._get_current_object()
    )
    db.session.add(photo)
    db.session.commit()
  return render_template('main/upload.html')


@main_bp.route('/photo/<int:photo_id>')
# @cache.cached(timeout=15*60, query_string=True)
def show_photo(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_MANAGE_COMMENT_PER_PAGE']
  pagination = Comment.query.with_parent(photo).order_by(Comment.timestamp.desc()) \
                            .paginate(page=page, per_page=per_page)
  comments = pagination.items

  comment_form = CommentForm()
  description_form = DescriptionForm()
  tag_form = TagForm()

  description_form.description.data = photo.description
  return render_template('main/photo.html', photo=photo,
                          comments=comments, pagination=pagination, tag_form = tag_form,
                          comment_form=comment_form, description_form=description_form,
                        )


@main_bp.route('/photo/n/<int:photo_id>')
def photo_next(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  photo_n = Photo.query.with_parent(photo.author).filter(Photo.id > photo_id) \
                        .order_by(Photo.id.asc()).first()
  if photo_n is None:
    flash('It is already the last one.', 'info')
    return redirect(url_for('.show_photo', photo_id=photo.id))
  return redirect(url_for('.show_photo', photo_id=photo_n.id))


@main_bp.route('/photo/p/<int:photo_id>')
def photo_prev(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  photo_p = Photo.query.with_parent(photo.author).filter(Photo.id < photo_id) \
                        .order_by(Photo.id.desc()).first()
  if photo_p is None:
    flash('It is already the first one.', 'info')
    return redirect(url_for('.show_photo', photo_id=photo.id))
  return redirect(url_for('.show_photo', photo_id=photo_p.id))


@main_bp.route('/collect/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
@permission_required('COLLECT')
def collect(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  if current_user.is_collecting(photo):
    flash('Already collected', 'info')
    return redirect(url_for('.show_photo', photo_id=photo_id))

  current_user.collect(photo)
  flash('Photo collected', 'success')
  if current_user != photo.author and photo.author.receive_collect_notification:
    push_collect_notification(
      collector=current_user, photo_id=photo_id, receiver=photo.author
    )
  return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/uncollect/<int:photo_id>', methods=['POST'])
@login_required
def uncollect(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  if not current_user.is_collecting(photo): 
    flash('Not collected yet.', 'info')
    return redirect(url_for('.show_photo', photo_id=photo_id))
  
  current_user.uncollect(photo)
  flash('Photo uncollected.', 'success')
  return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/report/comment/<int:comment_id>', methods=['POST'])
@login_required
@confirm_required
def report_comment(comment_id):
  comment = Comment.query.get_or_404(comment_id)
  comment.flag += 1
  db.session.commit()
  flash('Comment reported.', 'success')
  return redirect(url_for('.show_photo', photo_id=comment.photo_id))


@main_bp.route('/report/photo/<int:photo_id>', methods=['POST'])
@login_required
@confirm_required
def report_photo(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  photo.flag += 1
  db.session.commit()
  flash('Photo reported.', 'success')
  return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/photo/<int:photo_id>/collectors')
def show_collectors(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  page = request.args.get('page', 1, type=int)
  per_page = current_app.config['ALBUMY_USER_PER_PAGE']
  pagination = Collect.query.with_parent(photo) \
                .order_by(Collect.timestamp.asc()).paginate(page=page, per_page=per_page)
  collects = pagination.items
  return render_template('main/collectors.html', collects=collects, pagination=pagination, photo=photo)


@main_bp.route('/photo/<int:photo_id>/edit-description', methods=['POST'])
@login_required
def edit_description(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  if current_user != photo.author and not current_user.can('MODERATE'):
    abort(403)

  form = DescriptionForm()  
  if form.validate_on_submit():
    photo.description = form.description.data
    db.session.commit()
    flash('Description updated.', 'success')
  
  flash_errors(form)
  return redirect(url_for('.show_photo', photo_id=photo_id))


@main_bp.route('/photo/<int:photo_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(photo_id):
  photo = Photo.query.get_or_404(photo_id)
  page = request.args.get('page', 1, type=int)
  form = CommentForm()
  if form.validate_on_submit():
    comment = Comment(body = form.body.data, photo=photo,

demos/albumy/albumy/templates/user/_header.html
{% from 'macros.html' import follow_area with context %}
{% from 'bootstrap4/nav.html' import render_nav_item %}

<div class="row mb-3">
  <div class="col-md-3">
    <a href="{% if current_user == user %}{{ url_for('.change_avatar') }}{% else %}#{% endif %}">
      <img src="{{ url_for('main.get_avatar', filename=user.avatar_l) }}" class="img-fluid rounded" alt="">
    </a>
  </div>
  <div class="col-md-9">
    <h1>
      {{ user.name }}
      <small class="text-muted">{{ user.username }}</small>
    </h1>
    {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
    <p>
      {% if user.website %}
        <span class="oi oi-link-intact"></span>
        <a href="{{ user.website }}" 
          target="_blank">{{ user.website|truncate(30) }}</a>&nbsp;&nbsp;
      {% endif %}
      {% if user.location %}
        <span class="oi oi-map-marker"></span> 
        <a href="https://www.google.com/map?q={{ user.location }}"
          target="_blank">{{ user.location|truncate(30) }}</a>&nbsp;&nbsp;
      {% endif %}
      <span class="oi oi-calendar"></span>
      Joined {{ moment(user.member_since).format('LL') }}
    </p>
    <div>
      {% if current_user != user %}
        {% if current_user.can('MODERATE') %}
          {% if user.locked %}
            <form class="inline" method="post"
              action="{{ url_for('admin.unlock_user', user_id=user.id) }}">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <input type="submit" class="btn btn-secondary btn-sm" value="Unlock">
            </form> 
          {% else %}
            <form class="inline" method="post"
              action="{{ url_for('admin.lock_user', user_id=user.id) }}">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <input type="submit" class="btn btn-warning btn-sm" value="Lock">
            </form>
          {% endif %} 
          {% if user.active %}
            <form class="inline" method="post"
              action="{{ url_for('admin.block_user', user_id=user.id) }}">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <input type="submit" class="btn btn-warning btn-sm" value="Block">
            </form>
          {% else %}
            <form class="inline" method="post"
              action="{{ url_for('admin.unblock_user', user_id=user.id) }}">
              <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
              <input type="submit" class="btn btn-secondary btn-sm" value="Unblock">
            </form>
          {% endif %}
          <a class="btn btn-light btn-sm" href="mailto:{{ user.email }}">Email</a>
        {% endif %}
        {% if current_user.is_admin %}
          <a class="btn btn-warning btn-sm"
            href="{{ url_for('admin.edit_profile_admin', user_id=user.id) }}">Edit Profile.</a>
        {% endif %}
      {% endif %}
      <div class="float-right">
        {{ follow_area(user) }}
        {% if current_user.is_authenticated and user == current_user %}
          <a href="{{ url_for('.edit_profile') }}" class="btn btn-outline-primary btn-sm">Edit Profile</a> 
        {% endif %}
      </div>
    </div>
  </div>
</div>
<div class="user-nav">
  <ul class="nav nav-tabs">
    {{ render_nav_item('user.index', 'Photo', user.photos|length, username=user.username) }}
    {{ render_nav_item('user.show_collections', 'Collection', user.collections|length, username=user.username) }}
    {{ render_nav_item('user.show_following', 'Following', user.following.count() - 1, username=user.username) }}
    {{ render_nav_item('user.show_followers', 'Followers', user.followers.count() - 1, username=user.username) }}
  </ul>
</div>

demos/albumy/albumy/templates/user/collections.html
{% extends "base.html" %}
{% from 'bootstrap4/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name }}{% endblock title %}

{% block content %}
  {% include "user/_header.html" %}
  <h2>{{ user.name }}'s collection</h2>
  <div class="row">
    <div class="col-md-12">
      {% if user.public_collections or current_user == user %}
        {% if collects %}
          {% for collect in collects %}
            {{ photo_card(collect.collected) }} 
          {% endfor %} 
        {% else %}
          <div class="tip"><h3>No collection.</h3></div>
        {% endif %} 
      {% else %}
        <div class="tip"><h3>This user's collections was private.</h3></div>
      {% endif %}
    </div>
  </div>
  {% if collects %}
    <div class="page-footer">
      {{ render_pagination(pagination, align='center') }} 
    </div>
  {% endif %}
{% endblock content %}

demos/albumy/albumy/templates/user/followers.html
{% extends "base.html" %}
{% from 'bootstrap4/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}
  {{ user.name }}'s followers
{% endblock title %}

{% block content %}
  {% include "user/_header.html" %}
  <div class="row">
    <div class="col-md-12">
      {% if follows|length != 1 %}
        {% for follow in follows %}
          {% if follow.follower != user %}
            {{ user_card(follow.follower) }} 
          {% endif %} 
        {% endfor %} 
      {% else %}
        <div class="tip"><h3>No followers.</h3></div>
      {% endif %}
    </div>
  </div>
  {% if follows|length != 1 %}
    {{ render_pagination(pagination, align='center') }} 
  {% endif %}
{% endblock content %}

demos/albumy/albumy/templates/user/following.html
{% extends "base.html" %}
{% from 'bootstrap4/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}

{% block title %}
  {{ user.name }}'s following
{% endblock title %}

{% block content %}
  {% include "user/_header.html" %}
  <div class="row">
    <div class="col-md-12">
      {% if follows|length != 1 %}
        {% for follow in follows %}
          {% if follow.followed != user %}
            {{ user_card(follow.followed) }} 
          {% endif %}
        {% endfor %}
      {% else %}
        <div class="tip"><h3>No followings.</h3></div>
      {% endif %}
    </div>
  </div>
  {% if follows|length != 1 %}
    {{ render_pagination(pagination, align='center') }} 
  {% endif %}
{% endblock content  %}

demos/albumy/albumy/templates/user/index.html
{% extends "base.html" %}
{% from 'bootstrap4/pagination.html' import render_pagination %}
{% from 'macros.html' import photo_card %}

{% block title %}{{ user.name }}{% endblock title %}

{% block content %}
  {% include "user/_header.html" %}
  <div class="row">
    <div class="col-md-12">
      {% if photos %}
        {% for photo in photos %}
          {{ photo_card(photo) }} 
        {% endfor %} 
      {% else %}
        <div class="tip text-center">
          <h3>No photos.</h3>
          {% if user == current_user %}
            <a class="btn btn-link" href="{{ url_for('main.upload') }}">Upload</a> 
          {% else %}
            <a class="btn btn-link" href="{{ url_for('main.explore') }}">Explore</a>
          {% endif %}
        </div>
      {% endif %}
    </div>
  </div>
  {% if photos %}
    <div class="page-footer">
      {{ render_pagination(pagination, align='center') }}
    </div>
  {% endif %}
{% endblock content %}